pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin "@rails/request.js", to: "https://cdn.jsdelivr.net/npm/@rails/request.js@0.0.9/src/index.js"
pin "trix", to: "https://cdn.jsdelivr.net/npm/trix@2.1.0/dist/trix.esm.min.js"
pin "slim-select", to: "https://cdn.jsdelivr.net/npm/slim-select@2.8.1/dist/slimselect.es.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin_all_from "app/javascript/channels", under: "channels"
pin_all_from "app/javascript/config", under: "config"
